# Generated by Django 5.2.5 on 2025-09-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palabras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabracapturada',
            name='palabra_vinculada',
            field=models.CharField(help_text='Palabra vinculada al gesto (cualquier palabra personalizada)', max_length=50),
        ),
    ]
