# Generated by Django 5.2.5 on 2025-09-28 00:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticaVocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocal_objetivo', models.CharField(choices=[('A', 'Vocal A'), ('E', 'Vocal E'), ('I', 'Vocal I'), ('O', 'Vocal O'), ('U', 'Vocal U')], help_text='Vocal que se intentaba reconocer', max_length=1)),
                ('vocal_reconocida', models.CharField(blank=True, choices=[('A', 'Vocal A'), ('E', 'Vocal E'), ('I', 'Vocal I'), ('O', 'Vocal O'), ('U', 'Vocal U')], help_text='Vocal que fue reconocida', max_length=1, null=True)),
                ('fue_correcta', models.BooleanField(default=False, help_text='Indica si el reconocimiento fue correcto')),
                ('confianza', models.FloatField(help_text='Nivel de confianza del reconocimiento')),
                ('fecha_practica', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la práctica')),
                ('tiempo_respuesta', models.FloatField(blank=True, help_text='Tiempo en segundos que tomó el reconocimiento', null=True)),
            ],
            options={
                'verbose_name': 'Práctica de Vocal',
                'verbose_name_plural': 'Prácticas de Vocales',
                'ordering': ['-fecha_practica'],
            },
        ),
        migrations.CreateModel(
            name='VocalCapturada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocal_vinculada', models.CharField(choices=[('A', 'Vocal A'), ('E', 'Vocal E'), ('I', 'Vocal I'), ('O', 'Vocal O'), ('U', 'Vocal U')], help_text='Vocal vinculada al gesto', max_length=1)),
                ('tipo_mano', models.CharField(choices=[('left', 'Mano Izquierda'), ('right', 'Mano Derecha'), ('both', 'Ambas Manos')], default='right', help_text='Tipo de mano utilizada para el gesto', max_length=10)),
                ('nombre_display', models.CharField(help_text='Nombre descriptivo del gesto', max_length=50)),
                ('landmarks_data', models.TextField(help_text='Datos de landmarks de MediaPipe en formato JSON', validators=[django.core.validators.MinLengthValidator(10)])),
                ('landmarks_mano_izquierda', models.TextField(blank=True, help_text='Landmarks específicos de la mano izquierda', null=True)),
                ('landmarks_mano_derecha', models.TextField(blank=True, help_text='Landmarks específicos de la mano derecha', null=True)),
                ('numero_muestras', models.IntegerField(default=0, help_text='Número de muestras capturadas durante el entrenamiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del gesto')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el gesto está activo para reconocimiento')),
                ('precision_entrenamiento', models.FloatField(default=0.0, help_text='Precisión del gesto durante el entrenamiento (0.0 - 1.0)')),
            ],
            options={
                'verbose_name': 'Vocal Capturada',
                'verbose_name_plural': 'Vocales Capturadas',
                'ordering': ['vocal_vinculada', 'tipo_mano'],
            },
        ),
        migrations.CreateModel(
            name='HistorialReconocimientoVocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confianza', models.FloatField(help_text='Nivel de confianza del reconocimiento (0.0 - 1.0)')),
                ('fecha_reconocimiento', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del reconocimiento')),
                ('landmarks_reconocidos', models.TextField(blank=True, help_text='Landmarks detectados durante el reconocimiento')),
                ('vocal_reconocida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='vocales.vocalcapturada')),
            ],
            options={
                'verbose_name': 'Historial de Reconocimiento Vocal',
                'verbose_name_plural': 'Historial de Reconocimientos Vocales',
                'ordering': ['-fecha_reconocimiento'],
            },
        ),
    ]
