# Generated by Django 4.2.24 on 2025-09-30 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Identificador único de la sesión', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación de la sesión')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la sesión está activa')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario asociado a la sesión (opcional para usuarios anónimos)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Chat',
                'verbose_name_plural': 'Sesiones de Chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'Usuario'), ('bot', 'Bot'), ('system', 'Sistema')], default='user', help_text='Tipo de mensaje', max_length=10)),
                ('content', models.TextField(help_text='Contenido del mensaje')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del mensaje')),
                ('bot_confidence', models.FloatField(blank=True, help_text='Nivel de confianza de la respuesta del bot (0.0 - 1.0)', null=True)),
                ('bot_category', models.CharField(blank=True, help_text='Categoría identificada por el bot', max_length=50, null=True)),
                ('bot_redirect', models.CharField(blank=True, help_text='URL de redirección sugerida por el bot', max_length=200, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text='Dirección IP del usuario', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent del navegador', null=True)),
                ('session', models.ForeignKey(help_text='Sesión a la que pertenece el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot_educativo.chatsession')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages', models.PositiveIntegerField(default=0, help_text='Total de mensajes en la sesión')),
                ('user_messages', models.PositiveIntegerField(default=0, help_text='Mensajes del usuario')),
                ('bot_messages', models.PositiveIntegerField(default=0, help_text='Mensajes del bot')),
                ('average_confidence', models.FloatField(blank=True, help_text='Confianza promedio de las respuestas del bot', null=True)),
                ('session_duration', models.DurationField(blank=True, help_text='Duración total de la sesión', null=True)),
                ('most_common_category', models.CharField(blank=True, help_text='Categoría más común en la sesión', max_length=50, null=True)),
                ('session', models.OneToOneField(help_text='Sesión asociada a las analíticas', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='chatbot_educativo.chatsession')),
            ],
            options={
                'verbose_name': 'Analítica de Chat',
                'verbose_name_plural': 'Analíticas de Chat',
            },
        ),
    ]
