# Generated by Django 5.2.5 on 2025-09-20 23:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comando', models.CharField(max_length=255, verbose_name='Comando')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Comando',
                'verbose_name_plural': 'Comandos',
                'db_table': 'comandos',
                'ordering': ['-fecha'],
            },
        ),
    ]
