# Generated by Django 5.2.6 on 2025-09-26 05:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voz', '0002_usuario_comando_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombres', models.CharField(blank=True, max_length=150)),
                ('apellidos', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pending_registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voice_samples/')),
                ('audio_format', models.CharField(default='webm', max_length=10)),
                ('audio_duration', models.FloatField(blank=True, null=True)),
                ('audio_size', models.IntegerField(blank=True, null=True)),
                ('voice_embeddings', models.JSONField(blank=True, default=list)),
                ('voice_features', models.JSONField(blank=True, default=dict)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('pending_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_profiles', to='voz.pendingregistration')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pendingregistration',
            index=models.Index(fields=['token'], name='pending_reg_token_2516d5_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingregistration',
            index=models.Index(fields=['session_key'], name='pending_reg_session_d39a95_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingregistration',
            index=models.Index(fields=['expires_at'], name='pending_reg_expires_f06591_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceprofile',
            index=models.Index(fields=['user'], name='voice_profi_user_id_24748b_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceprofile',
            index=models.Index(fields=['pending_registration'], name='voice_profi_pending_fc8f69_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceprofile',
            index=models.Index(fields=['consent_given'], name='voice_profi_consent_454727_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceprofile',
            index=models.Index(fields=['is_active'], name='voice_profi_is_acti_eeaf22_idx'),
        ),
    ]
