# Generated by Django 5.2.5 on 2025-09-28 00:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LetraCapturada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra_vinculada', models.CharField(choices=[('A', 'Letra A'), ('B', 'Letra B'), ('C', 'Letra C'), ('D', 'Letra D'), ('E', 'Letra E'), ('F', 'Letra F'), ('G', 'Letra G'), ('H', 'Letra H'), ('I', 'Letra I'), ('J', 'Letra J'), ('K', 'Letra K'), ('L', 'Letra L'), ('M', 'Letra M'), ('N', 'Letra N'), ('O', 'Letra O'), ('P', 'Letra P'), ('Q', 'Letra Q'), ('R', 'Letra R'), ('S', 'Letra S'), ('T', 'Letra T'), ('U', 'Letra U'), ('V', 'Letra V'), ('W', 'Letra W'), ('X', 'Letra X'), ('Y', 'Letra Y'), ('Z', 'Letra Z')], help_text='Letra vinculada al gesto', max_length=1)),
                ('tipo_mano', models.CharField(choices=[('left', 'Mano Izquierda'), ('right', 'Mano Derecha'), ('both', 'Ambas Manos')], default='right', help_text='Tipo de mano utilizada para el gesto', max_length=10)),
                ('nombre_display', models.CharField(help_text='Nombre descriptivo del gesto', max_length=50)),
                ('landmarks_data', models.TextField(help_text='Datos de landmarks de MediaPipe en formato JSON', validators=[django.core.validators.MinLengthValidator(10)])),
                ('landmarks_mano_izquierda', models.TextField(blank=True, help_text='Landmarks específicos de la mano izquierda', null=True)),
                ('landmarks_mano_derecha', models.TextField(blank=True, help_text='Landmarks específicos de la mano derecha', null=True)),
                ('numero_muestras', models.IntegerField(default=0, help_text='Número de muestras capturadas durante el entrenamiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del gesto')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el gesto está activo para reconocimiento')),
                ('precision_entrenamiento', models.FloatField(default=0.0, help_text='Precisión del gesto durante el entrenamiento (0.0 - 1.0)')),
            ],
            options={
                'verbose_name': 'Letra Capturada',
                'verbose_name_plural': 'Letras Capturadas',
                'ordering': ['letra_vinculada', 'tipo_mano'],
            },
        ),
        migrations.CreateModel(
            name='PracticaLetra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra_objetivo', models.CharField(choices=[('A', 'Letra A'), ('B', 'Letra B'), ('C', 'Letra C'), ('D', 'Letra D'), ('E', 'Letra E'), ('F', 'Letra F'), ('G', 'Letra G'), ('H', 'Letra H'), ('I', 'Letra I'), ('J', 'Letra J'), ('K', 'Letra K'), ('L', 'Letra L'), ('M', 'Letra M'), ('N', 'Letra N'), ('O', 'Letra O'), ('P', 'Letra P'), ('Q', 'Letra Q'), ('R', 'Letra R'), ('S', 'Letra S'), ('T', 'Letra T'), ('U', 'Letra U'), ('V', 'Letra V'), ('W', 'Letra W'), ('X', 'Letra X'), ('Y', 'Letra Y'), ('Z', 'Letra Z')], help_text='Letra que se intentaba reconocer', max_length=1)),
                ('letra_reconocida', models.CharField(blank=True, choices=[('A', 'Letra A'), ('B', 'Letra B'), ('C', 'Letra C'), ('D', 'Letra D'), ('E', 'Letra E'), ('F', 'Letra F'), ('G', 'Letra G'), ('H', 'Letra H'), ('I', 'Letra I'), ('J', 'Letra J'), ('K', 'Letra K'), ('L', 'Letra L'), ('M', 'Letra M'), ('N', 'Letra N'), ('O', 'Letra O'), ('P', 'Letra P'), ('Q', 'Letra Q'), ('R', 'Letra R'), ('S', 'Letra S'), ('T', 'Letra T'), ('U', 'Letra U'), ('V', 'Letra V'), ('W', 'Letra W'), ('X', 'Letra X'), ('Y', 'Letra Y'), ('Z', 'Letra Z')], help_text='Letra que fue reconocida', max_length=1, null=True)),
                ('fue_correcta', models.BooleanField(default=False, help_text='Indica si el reconocimiento fue correcto')),
                ('confianza', models.FloatField(help_text='Nivel de confianza del reconocimiento')),
                ('fecha_practica', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la práctica')),
                ('tiempo_respuesta', models.FloatField(blank=True, help_text='Tiempo en segundos que tomó el reconocimiento', null=True)),
            ],
            options={
                'verbose_name': 'Práctica de Letra',
                'verbose_name_plural': 'Prácticas de Letras',
                'ordering': ['-fecha_practica'],
            },
        ),
        migrations.CreateModel(
            name='HistorialReconocimientoLetra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confianza', models.FloatField(help_text='Nivel de confianza del reconocimiento (0.0 - 1.0)')),
                ('fecha_reconocimiento', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del reconocimiento')),
                ('landmarks_reconocidos', models.TextField(blank=True, help_text='Landmarks detectados durante el reconocimiento')),
                ('letra_reconocida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='abecedario.letracapturada')),
            ],
            options={
                'verbose_name': 'Historial de Reconocimiento Letra',
                'verbose_name_plural': 'Historial de Reconocimientos Letras',
                'ordering': ['-fecha_reconocimiento'],
            },
        ),
    ]
