# Generated by Django 5.2.6 on 2025-09-20 09:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GestoMano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gesto', models.CharField(choices=[('0', 'Número 0'), ('1', 'Número 1'), ('2', 'Número 2'), ('3', 'Número 3'), ('4', 'Número 4'), ('5', 'Número 5'), ('6', 'Número 6'), ('7', 'Número 7'), ('8', 'Número 8'), ('9', 'Número 9'), ('+', 'Suma (+)'), ('-', 'Resta (-)'), ('*', 'Multiplicación (*)'), ('/', 'División (/)'), ('=', 'Igual (=)')], help_text='Tipo de gesto (número u operación)', max_length=20, unique=True)),
                ('nombre_display', models.CharField(help_text='Nombre descriptivo del gesto', max_length=50)),
                ('landmarks_data', models.TextField(help_text='Datos de landmarks de MediaPipe en formato JSON', validators=[django.core.validators.MinLengthValidator(10)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del gesto')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el gesto está activo para reconocimiento')),
                ('precision_entrenamiento', models.FloatField(default=0.0, help_text='Precisión del gesto durante el entrenamiento (0.0 - 1.0)')),
            ],
            options={
                'verbose_name': 'Gesto de Mano',
                'verbose_name_plural': 'Gestos de Mano',
                'ordering': ['tipo_gesto'],
            },
        ),
        migrations.CreateModel(
            name='HistorialReconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confianza', models.FloatField(help_text='Nivel de confianza del reconocimiento (0.0 - 1.0)')),
                ('fecha_reconocimiento', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del reconocimiento')),
                ('landmarks_reconocidos', models.TextField(blank=True, help_text='Landmarks detectados durante el reconocimiento')),
                ('gesto_reconocido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='operaciones.gestomano')),
            ],
            options={
                'verbose_name': 'Historial de Reconocimiento',
                'verbose_name_plural': 'Historial de Reconocimientos',
                'ordering': ['-fecha_reconocimiento'],
            },
        ),
        migrations.CreateModel(
            name='OperacionMatematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operando1', models.CharField(help_text='Primer operando de la operación', max_length=10)),
                ('operador', models.CharField(choices=[('+', 'Suma'), ('-', 'Resta'), ('*', 'Multiplicación'), ('/', 'División')], help_text='Operador matemático', max_length=1)),
                ('operando2', models.CharField(help_text='Segundo operando de la operación', max_length=10)),
                ('resultado', models.CharField(help_text='Resultado de la operación', max_length=20)),
                ('fecha_operacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la operación')),
                ('gestos_utilizados', models.ManyToManyField(help_text='Gestos utilizados en esta operación', to='operaciones.gestomano')),
            ],
            options={
                'verbose_name': 'Operación Matemática',
                'verbose_name_plural': 'Operaciones Matemáticas',
                'ordering': ['-fecha_operacion'],
            },
        ),
    ]
