# Generated by Django 5.2.6 on 2025-09-20 01:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GestureFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre único de la función', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('function_type', models.CharField(choices=[('math', 'Operación Matemática'), ('command', 'Comando Personalizado'), ('action', 'Acción del Sistema')], default='command', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Descripción de lo que hace la función')),
                ('code', models.TextField(help_text='Código o comando que se ejecutará')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Parámetros adicionales para la función')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gesture_functions',
                'indexes': [models.Index(fields=['name'], name='gesture_fun_name_7e09e2_idx'), models.Index(fields=['function_type'], name='gesture_fun_functio_280761_idx')],
            },
        ),
        migrations.CreateModel(
            name='Gesture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre único del gesto para el usuario', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('gesture_type', models.CharField(choices=[('static', 'Gesto Estático'), ('dynamic', 'Gesto Dinámico')], default='static', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Descripción del gesto')),
                ('feature_data', models.JSONField(default=dict, help_text='Datos de características extraídas del gesto')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('training', 'En Entrenamiento'), ('trained', 'Entrenado'), ('active', 'Activo'), ('inactive', 'Inactivo')], default='draft', max_length=20)),
                ('accuracy', models.FloatField(default=0.0, help_text='Precisión del modelo entrenado (0-1)')),
                ('confidence_threshold', models.FloatField(default=0.7, help_text='Umbral de confianza para reconocimiento (0-1)')),
                ('training_samples_count', models.PositiveIntegerField(default=0)),
                ('last_trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestures', to=settings.AUTH_USER_MODEL)),
                ('gesture_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestures', to='operaciones.gesturefunction')),
            ],
            options={
                'db_table': 'gestures',
            },
        ),
        migrations.CreateModel(
            name='RecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognized_gesture_name', models.CharField(help_text='Nombre del gesto reconocido', max_length=100)),
                ('confidence_score', models.FloatField(help_text='Puntuación de confianza del reconocimiento (0-1)')),
                ('execution_successful', models.BooleanField(default=False, help_text='Indica si la función asociada se ejecutó correctamente')),
                ('execution_result', models.TextField(blank=True, help_text='Resultado de la ejecución de la función')),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processing_time_ms', models.PositiveIntegerField(default=0, help_text='Tiempo de procesamiento en milisegundos')),
                ('gesture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recognition_logs', to='operaciones.gesture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recognition_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(help_text='Nombre de la sesión de entrenamiento', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('training_data', models.JSONField(default=list, help_text='Muestras de entrenamiento capturadas')),
                ('samples_count', models.PositiveIntegerField(default=0)),
                ('accuracy_achieved', models.FloatField(blank=True, help_text='Precisión alcanzada en esta sesión', null=True)),
                ('loss_value', models.FloatField(blank=True, help_text='Valor de pérdida del entrenamiento', null=True)),
                ('epochs', models.PositiveIntegerField(default=100)),
                ('learning_rate', models.FloatField(default=0.001)),
                ('batch_size', models.PositiveIntegerField(default=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gesture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='operaciones.gesture')),
            ],
            options={
                'db_table': 'training_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GestureSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmark_data', models.JSONField(help_text='Datos de landmarks de MediaPipe para esta muestra')),
                ('features', models.JSONField(default=dict, help_text='Características extraídas de la muestra')),
                ('capture_timestamp', models.DateTimeField(auto_now_add=True)),
                ('quality_score', models.FloatField(default=1.0, help_text='Puntuación de calidad de la muestra (0-1)')),
                ('is_valid', models.BooleanField(default=True, help_text='Indica si la muestra es válida para entrenamiento')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='operaciones.trainingsession')),
            ],
            options={
                'db_table': 'gesture_samples',
                'ordering': ['capture_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='gesture',
            index=models.Index(fields=['user', 'name'], name='gestures_user_id_dcb0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='gesture',
            index=models.Index(fields=['status'], name='gestures_status_5f5fab_idx'),
        ),
        migrations.AddIndex(
            model_name='gesture',
            index=models.Index(fields=['gesture_type'], name='gestures_gesture_2a80c8_idx'),
        ),
        migrations.AddIndex(
            model_name='gesture',
            index=models.Index(fields=['user', 'status'], name='gestures_user_id_c32034_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gesture',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='recognitionlog',
            index=models.Index(fields=['user', 'timestamp'], name='recognition_user_id_7f4a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionlog',
            index=models.Index(fields=['gesture', 'timestamp'], name='recognition_gesture_0a26aa_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionlog',
            index=models.Index(fields=['timestamp'], name='recognition_timesta_7a235f_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['gesture', 'status'], name='training_se_gesture_efa283_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['created_at'], name='training_se_created_400f92_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['status'], name='training_se_status_a5ce9e_idx'),
        ),
        migrations.AddIndex(
            model_name='gesturesample',
            index=models.Index(fields=['training_session', 'is_valid'], name='gesture_sam_trainin_0a5cff_idx'),
        ),
        migrations.AddIndex(
            model_name='gesturesample',
            index=models.Index(fields=['capture_timestamp'], name='gesture_sam_capture_031a94_idx'),
        ),
    ]
