# Generated by Django 5.2.6 on 2025-09-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestomano',
            options={'ordering': ['tipo_gesto', 'tipo_mano'], 'verbose_name': 'Gesto de Mano', 'verbose_name_plural': 'Gestos de Mano'},
        ),
        migrations.AddField(
            model_name='gestomano',
            name='landmarks_mano_derecha',
            field=models.TextField(blank=True, help_text='Landmarks específicos de la mano derecha', null=True),
        ),
        migrations.AddField(
            model_name='gestomano',
            name='landmarks_mano_izquierda',
            field=models.TextField(blank=True, help_text='Landmarks específicos de la mano izquierda', null=True),
        ),
        migrations.AddField(
            model_name='gestomano',
            name='numero_muestras',
            field=models.IntegerField(default=0, help_text='Número de muestras capturadas durante el entrenamiento'),
        ),
        migrations.AddField(
            model_name='gestomano',
            name='tipo_mano',
            field=models.CharField(choices=[('left', 'Mano Izquierda'), ('right', 'Mano Derecha'), ('both', 'Ambas Manos')], default='right', help_text='Tipo de mano utilizada para el gesto', max_length=10),
        ),
        migrations.AlterField(
            model_name='gestomano',
            name='tipo_gesto',
            field=models.CharField(choices=[('0', 'Número 0'), ('1', 'Número 1'), ('2', 'Número 2'), ('3', 'Número 3'), ('4', 'Número 4'), ('5', 'Número 5'), ('6', 'Número 6'), ('7', 'Número 7'), ('8', 'Número 8'), ('9', 'Número 9'), ('+', 'Suma (+)'), ('-', 'Resta (-)'), ('*', 'Multiplicación (*)'), ('/', 'División (/)'), ('=', 'Igual (=)')], help_text='Tipo de gesto (número u operación)', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='gestomano',
            unique_together={('tipo_gesto', 'tipo_mano')},
        ),
    ]
