# Generated by Django 5.2.6 on 2025-09-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_alter_gestomano_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestomano',
            options={'ordering': ['numero_vinculado', 'operacion_vinculada', 'tipo_mano'], 'verbose_name': 'Gesto de Mano', 'verbose_name_plural': 'Gestos de Mano'},
        ),
        migrations.AlterUniqueTogether(
            name='gestomano',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gestomano',
            name='numero_vinculado',
            field=models.IntegerField(blank=True, help_text='Número del 0 al 50 vinculado al gesto', null=True),
        ),
        migrations.AddField(
            model_name='gestomano',
            name='operacion_vinculada',
            field=models.CharField(blank=True, choices=[('suma', 'Suma (+)'), ('resta', 'Resta (-)'), ('multiplicacion', 'Multiplicación (×)'), ('division', 'División (÷)')], help_text='Operación matemática vinculada al gesto', max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='gestomano',
            name='tipo_gesto',
        ),
    ]
